apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: lab3
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
       app: mysql
    spec:
      volumes:
       - name: mysql-data
         persistentVolumeClaim:
           claimName: mysql-pvc
      containers:
      - name: mysql
        image: 563571752566.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: mysql
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
 
