apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  namespace: app
  labels:
    app: employees
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
       app: employees
    spec:
     containers:
      - name: employees-webapp
        image: 466548522055.dkr.ecr.us-east-1.amazonaws.com/ass03-app:v3.0
        env:
       - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DBHOST
           value: "mysqldb.lab3"
        - name: DBPORT
           value: "3306"
        - name: DATABASE
           value: "employees"
        - name: APP_COLOR
           value: "darkblue"
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP