apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  namespace: app
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
       app: employees
    spec:
     containers:
      - name: employees-webapp
        image: 466548522055.dkr.ecr.us-east-1.amazonaws.com/ass02-app:v2.0
        env:
        - name: DBHOST
          valueFrom:
             secretKeyRef:
               name: app-secrets
               key: DBHOST
        - name: DBPORT
          valueFrom:
             secretKeyRef:
               name: app-secrets
               key: DBPORT  
        - name: DBPWD
          valueFrom:
             secretKeyRef:
               name: app-secrets
               key: DBPWD
        - name: DATABASE
          valueFrom:
             secretKeyRef:
               name: app-secrets
               key: DATABASE
        - name: DBUSER
          valueFrom:
             secretKeyRef:
               name: app-secrets
               key: DBUSER
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP