apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-employee
  namespace: db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
       app: mysql
    spec:
      containers:
      - name: mysql
        image: 466548522055.dkr.ecr.us-east-1.amazonaws.com/ass02-db:v2.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
