apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: lab3
  labels:
    app: mysql
spec:
  storageClassName: localstorage
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data