apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: localstorage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce