apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-local
  namespace: lab3
  labels: 
    app: mysql
spec:
  storageClassName: localstorage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce