apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc1
  namespace: lab3
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
  - ReadWriteOnce
  #storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  