apiVersion: v1
kind: Namespace
metadata:
  name: lab3
  labels:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: lab3
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql